### PR TITLE
Fix: The Roadmap page could be better

### PR DESCRIPTION
**Pull request by pragyananda**

### CODE REVIEW

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
Thanks for the patch. After the changes, there is actually no link to the GitHub Project in the beginning of the page. Could you please restore it?

**Comment by pragyananda** [comment]
hello, @oleg-nenashev sorry I didn't understand 
you were talking about the GitHub project at the beginning of the page but I am also not added.

**Comment by oleg-nenashev** [comment]
What I meant is that this change removed the reference https://github.com/orgs/gradle/projects/31/views/1 in the beginning of the page . It would be nice to restore it, preferably in a more visible form (e.g. a button or a badge)

**Comment by pragyananda** [comment]
is this better?

**Review by oleg-nenashev — COMMENTED** [review]
Just a few items before we merge:

* WhiIe I understand the changes in the legal text and agree with them, it is better to not change anything in legal notices without confirming with legal. I suggest reverting that part as not critical
* Not a blocker - It would be nice to move the images to a sub-directory like `/images`

**Review by oleg-nenashev — APPROVED** [review]
Thank you for the patch. I will get it integrated and maybe polish a bit in the follow-ups

**Pull request merged**
